PROJECT := main

SEARCH :=

HEADERS := $(wildcard *.hpp)

SOURCES :=

TARGET := arduino_due

SERIAL_PORT := COM7

HEAP := BMPTK

RUN_PAUSE := echo "Run complete"

include $(RTOS)/makefile.inc
include $(HWLIB)/makefile.inc