PROJECT := main

SEARCH :=

HEADERS := $(wildcard *.hpp)

SOURCES := ir_sender.cpp

TARGET := arduino_due

SERIAL_PORT := COM9

HEAP := BMPTK

RUN_PAUSE := echo "Run complete"

include $(RTOS)/makefile.inc
include $(HWLIB)/makefile.inc